---
- name: Create Domoticz src dir
  file:
    path: "{{ domoticz_download_dir }}/{{ domoticz_src }}"
    state: directory
    owner: "{{ domoticz_user }}"
    group: "{{ domoticz_group }}"

- name: GET Domoticz (No SSL due lack of SNI support)
  get_url:
    url: "{{ domoticz_url | replace('https', 'http') }}"
    dest: "{{ domoticz_download_dir }}/{{ domoticz_src }}.tar.gz"
    validate_certs: true
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version == '7') or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int <= 14.04)

- name: GET Domoticz
  get_url:
    url: "{{ domoticz_url }}"
    dest: "{{ domoticz_download_dir }}/{{ domoticz_src }}.tar.gz"

- name: Unpack Domoticz source files
  unarchive:
    src: "{{ domoticz_download_dir }}/{{ domoticz_src }}.tar.gz"
    dest: "{{ domoticz_download_dir }}/{{ domoticz_src }}"
    owner: "{{ domoticz_user }}"
    group: "{{ domoticz_group }}"
    remote_src: true

- block:
    - name: Move init script for using systemd
      template:
        src: domoticz/init-systemd.j2
        dest: "{{ domoticz_init }}"
        owner: root
        group: root
        mode: 0775

    - name: Autostart Domoticz and restart service
      systemd:
        name: domoticz
        enabled: true
        daemon_reload: true
      notify: restart domoticz

  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7") or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 15.04) or
        (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 8)

- block:
    - name: Setup Software Collections
      yum:
        name: centos-release-scl
        state: present

    - name: Setup Python 3.3
      yum:
        name: python33
        state: present

    - name: Move init script Centos 6
      template:
        src: domoticz/init-centos-fedora.j2
        dest: "{{ domoticz_init }}"
        owner: root
        group: root
        mode: 0775
      notify: restart plexpy

    - name: Autostart Domoticz and restart service
      service:
        name: domoticz
        enabled: true
      notify: restart domoticz

  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- block:
    - name: Move init script for using init.d
      template:
        src: domoticz/init-initd.j2
        dest: "{{ domoticz_init }}"
        owner: root
        group: root
        mode: 0775

    - name: Autostart Domoticz and restart service
      service:
        name: domoticz
        enabled: true
      notify: restart domoticz

  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6') or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int <= 15.10)
